### ISSUE TITLE
docs: stop mentioning Vance in all docs

### ISSUE THREAD

**Issue by JieDing** [linkall-labs/docs#102]
## Documentation

Please answer these questions before submitting your issue. Thanks!

### 1. What kind of enhancement do you need to improve Vanus documentation? (Required)

- [ ] Fix typos or format(punctuation, space, indentation, code block, etc.)
- [x] Update inappropriate or misunderstanding content
- [ ] Add missing content or new documents
- [ ] Delete useless content or outdated documents
- [ ] Localize or translate documents

### 2. Tell us more about enhancement you need (Required)

It would be better if we don't mention Vance currently. 
https://docs.linkall.com/introduction/concepts
https://docs.linkall.com/introduction/architecture

### 3. Are you willing to solve this issue?
@VedaGao Plz solve this issue.

**Comment by Michaelg22** [comment]
https://github.com/linkall-labs/docs/pull/107

**Comment by Michaelg22** [comment]
https://github.com/linkall-labs/docs/pull/107

**Comment by JieDing** [comment]
The issue is resolved.
