### ISSUE TITLE
docs: add a screenshot of "Edit this page" link to the README.md

### ISSUE THREAD

**Issue by nikitakoselev** [linkall-labs/docs#192]
## Documentation

Please answer these questions before submitting your issue. Thanks!

### 1. What kind of enhancement do you need to improve Vanus documentation? (Required)

- [ ] Fix typos or format(punctuation, space, indentation, code block, etc.)
- [ ] Update inappropriate or misunderstanding content
- [x ] Add missing content or new documents
- [ ] Delete useless content or outdated documents
- [ ] Localize or translate documents

### 2. Tell us more about enhancement you need (Required)
The readme file only mentions the "Edit this page" link, but doesn't show what this button look like.
https://github.com/linkall-labs/docs/blob/main/README.md mentions "If you want to contribute to the documentation, you can open an issue or use the Edit this page pencil icon on the bottom of each page of the website.".
<img width="764" alt="image" src="https://user-images.githubusercontent.com/6383738/209775573-791ba49d-aa45-41d0-98b4-d77032472b3e.png">

The link:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/6383738/209775780-55720bbf-d6e1-4300-9344-b27d2f747536.png">

### 3. Are you willing to solve this issue?
Yes, but I would prefer for the item to be marked as "good first time issue", so somebody junior could make her/their/his first #OpenSource contribution.

**Comment by JieDing** [comment]
@nikitakoselev Thanks for your kind suggestion. Just labeled it "good first issue"

**Comment by Rhythm-08** [comment]
I want to work on this issue can you assign this task to me .

**Comment by JieDing** [comment]
> I want to work on this issue can you assign this task to me .

Sure, we appreciate it.

**Comment by JieDing** [comment]
> I want to work on this issue can you assign this task to me .

Please read [contributing guide](https://github.com/linkall-labs/docs/blob/main/CONTRIBUTING.md#sign-your-work) first. If you met any issues fell free to let us know about it.
