### ISSUE TITLE
[Good First Issues]: update doc "community/community-events/top-10-active-contributors-2022.md" - 2 points

### ISSUE THREAD

**Issue by JieDing** [linkall-labs/docs#198]
# Motivation
The best way to learn about an open-source project starts from reading its documentation. In order to better know about Vanus and improve the quality of Vanus documentation, we're looking for OSS enthusiasts to review our docs.

# Details

Add a new link in the [documentation of community events](https://github.com/linkall-labs/docs/blob/main/community/community-events/top-10-active-contributors-2022.md).

# How to change

1. Fork the docs repository.
2. Create a branch update-event
3. Update file `community/community-events/top-10-active-contributors-2022.md`
4. Under the line `- [Vanus documentation good-first-time issues](https://github.com/linkall-labs/docs/issues/124)`, add a new link with the name `Vanus Connect good-first-time issues` and the link `https://github.com/linkall-labs/vance/issues/131`.
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/10882129/210087288-51963efc-cdbb-499c-b37b-803bb198f1e2.png">
5. Replace the line `Each PR of Vanus functions good-first-time issues will be counted 10 points.`  with `Each PR of Vanus functions good-first-time issues will be counted from 5 to 10 points.`.
6. Submit your PR

# Contribution points
Each issue counts specific points based on its difficulty. Contributors earn the corresponding points if they solve that issue. Contribution points are used to describe the contributions contributors have made. They can also be used to get rewards when there are community events.

This issue counts 2 points.

# How to claim to solve this issue
If you want to solve this issue, please leave a comment in this issue like:

> I'd like to solve the issue, please assign it to me.

Vanus community will assign the issue to you on time.

**Comment by pawanmkr** [comment]
I'd like to solve the issue, please assign it to me.

**Comment by gauravmnjwr** [comment]
Hey there, I'd like to work on this documentation

**Comment by JieDing** [comment]
> Hey there, I'd like to work on this documentation

Sorry @gauravmnjwr , this issue is finished, please help us with other issues

**Comment by JieDing** [comment]
Issue is resolved in #204
