### ISSUE TITLE
[Good First Issues]: update doc "https://github.com/linkall-labs/docs/blob/main/content/how-to/use-gcloud-functions.md" - 2 points

### ISSUE THREAD

**Issue by VedaGao** [linkall-labs/docs#200]
# Motivation
The best way to learn about an open-source project starts with reading its documentation. In order to better know about Vanus and improve the quality of Vanus documentation, we're looking for OSS enthusiasts to review our docs.

# Details

Replace two links in the [Use Cloud Functions](https://github.com/linkall-labs/docs/blob/main/content/how-to/use-gcloud-functions.md).

# How to change

1. Fork the docs repository.
2. Create a branch update-event
3. Update file `linkall-labs/docs/blob/main/content/how-to/use-gcloud-functions.md`
4. In "Have a running Vanus cluster" in the section of Prerequisites, replace the link `- [Vanus](https://github.com/linkall-labs/docs/blob/main/user-manual/getting-started/install/k8s(recommended).md)`, with the link `https://github.com/linkall-labs/docs/blob/main/content/getting-started/installation.mdx`.
5. Replace the link `[vsctl](https://github.com/linkall-labs/docs/blob/main/user-manual/how-to/vsctl.md)`  with `[vsctl](https://github.com/linkall-labs/docs/blob/main/content/how-to/vsctl.md)`.
![m5bZiCAjta](https://user-images.githubusercontent.com/103040022/210087997-b5e02181-3684-4940-ad10-8cea0df9cf6a.jpg)
6. Submit your PR

# Contribution points
Each issue counts specific points based on its difficulty. Contributors earn the corresponding points if they solve that issue. Contribution points are used to describe the contributions contributors have made. They can also be used to get rewards when there are community events.

This issue counts 2 points.

# How to claim to solve this issue
If you want to solve this issue, please leave a comment on this issue like:

> I'd like to solve the issue, please assign it to me.

Vanus community will assign the issue to you on time.

**Comment by DevanshSahni** [comment]
I'd like to solve the issue, please assign it to me.

**Comment by DevanshSahni** [comment]
Hey! I have made the PR but I am getting this DCO check issue. Can you please help me with that?

**Comment by JieDing** [comment]
> Hey! I have made the PR but I am getting this DCO check issue. Can you please help me with that?

Please go through this to solve your DCO problem. https://github.com/linkall-labs/docs/blob/main/CONTRIBUTING.md#sign-your-work

**Comment by Michaelg22** [comment]
Thank you for your contribution. You have been awarded 2 points. This issue was fixed and merged
