### ISSUE TITLE
[Good First Issues]: update doc "linkall-labs/docs/blob/main/content/how-to/use-lambda.md" - 1 point

### ISSUE THREAD

**Issue by VedaGao** [linkall-labs/docs#201]
## Documentation

# Motivation
The best way to learn about an open-source project starts with reading its documentation. In order to better know about Vanus and improve the quality of Vanus documentation, we're looking for OSS enthusiasts to review our docs.

# Details

Replace two links in the [Use Lambda](https://github.com/linkall-labs/docs/blob/main/content/how-to/use-lambda.md).

# How to change

1. Fork the docs repository.
2. Create a branch update-event
3. Update file `linkall-labs/docs/blob/main/content/how-to/use-lambda.md`
4. In "Have a running Vanus cluster" in the section of Prerequisites, replace the link `- [Vanus](https://github.com/linkall-labs/docs/blob/main/user-manual/getting-started/install/k8s(recommended).md)`, with the link `https://github.com/linkall-labs/docs/blob/main/content/getting-started/installation.mdx`.
5. Replace the link `[vsctl](https://github.com/linkall-labs/docs/blob/main/user-manual/how-to/vsctl.md)`  with `[vsctl](https://github.com/linkall-labs/docs/blob/main/content/how-to/vsctl.md)`.
![image](https://user-images.githubusercontent.com/103040022/210089934-ee739fa2-b9a6-4e30-9186-fb200c634463.png)
6. Submit your PR

# Contribution points
Each issue counts specific points based on its difficulty. Contributors earn the corresponding points if they solve that issue. Contribution points are used to describe the contributions contributors have made. They can also be used to get rewards when there are community events.

This issue counts 1 point.

# How to claim to solve this issue
If you want to solve this issue, please leave a comment on this issue like:

> I'd like to solve the issue, please assign it to me.

Vanus community will assign the issue to you on time.

**Comment by shivam-sharma7** [comment]
can you assign me / @VedaGao

**Comment by NileshMS** [comment]
could you please assign it to me!! @VedaGao

**Comment by VedaGao** [comment]
> can you assign me / @VedaGao

first of all thanks so much for being interested in contributing to us. However 1-point issues are prepared with the lowest difficulties for those beginners to quickly get started to contribute. So generally speaking, each contributor can be assigned with 1-point task once. Please find other [first good issues](https://github.com/linkall-labs/docs/labels/good%20first%20issue) to help us. Thanks again.

**Comment by VedaGao** [comment]
> could you please assign it to me!! @VedaGao



> assign

Already assigned to you, thanks.
