### ISSUE TITLE
[Good First Issues]: update doc "linkall-labs/docs/blob/main/content/how-to/produce/send-delay-event.md" - 1 point

### ISSUE THREAD

**Issue by VedaGao** [linkall-labs/docs#209]
## Documentation

# Motivation
The best way to learn about an open-source project starts with reading its documentation. In order to better know about Vanus and improve the quality of Vanus documentation, we're looking for OSS enthusiasts to review our docs.

# Details

Replace two links in the [Send an event with delay using the CloudEvents SDK](https://github.com/linkall-labs/docs/blob/main/content/how-to/produce/send-delay-event.md).

# How to change

1. Fork the docs repository.
2. Create a branch update-event
3. Update file `linkall-labs/docs/blob/main/content/how-to/produce/send-delay-event.md`
4. In "Have a running Vanus cluster" in the section of Prerequisites, replace the link `- [Vanus](https://github.com/linkall-labs/docs/blob/main/user-manual/getting-started/install/k8s(recommended).md)`, with the link `/getting-started/installation`.
5. Replace the link `[vsctl](https://github.com/linkall-labs/docs/blob/main/user-manual/how-to/vsctl.md)`  with `[vsctl](/how-to/vsctl)`.
![image](https://user-images.githubusercontent.com/103040022/210357298-eef7e3ad-18cc-4221-8a35-cab72938ebfb.png)
6. Submit your PR

# Contribution points
Each issue counts specific points based on its difficulty. Contributors earn the corresponding points if they solve that issue. Contribution points are used to describe the contributions contributors have made. They can also be used to get rewards when there are community events.

This issue counts 1 point.

# How to claim to solve this issue
If you want to solve this issue, please leave a comment on this issue like:

> I'd like to solve the issue, please assign it to me.

Vanus community will assign the issue to you on time.

**Comment by shivam-sharma7** [comment]
can you assign me?

**Comment by JieDing** [comment]
> can you assign me? / @VedaGao

Yeah I will assign it to you, please check out the latest link

<img width="806" alt="image" src="https://user-images.githubusercontent.com/10882129/210370683-2805e2f9-e61b-426e-840a-99994b879801.png">

**Comment by JieDing** [comment]
fixed in #210
