### ISSUE TITLE
[Good First Issues]: Update Transformer Concept "linkall-labs/docs/blob/main/content/introduction/concepts.md" worth 4 Points

### ISSUE THREAD

**Issue by Michaelg22** [linkall-labs/docs#222]
Documentation

Motivation

The best way to learn about an open-source project starts with reading its documentation. In order to better know about Vanus and improve the quality of Vanus documentation, we're looking for OSS enthusiasts to review our docs.

Details

Rewrite the concept of transformer in the documentation. The Concept should introduce the idea of the transformer tool and briefly the idea of Define, Function, and template. You can look at the "How to Transformer Document" to help you better. Also the concept should be simple and a concept, not how to. 

How to change it: 
<img width="512" alt="Screen Shot 2023-01-10 at 16 37 42" src="https://user-images.githubusercontent.com/62085623/211504728-26a8e37f-e81a-437f-8594-7ee11892a359.png">

1. Fork the docs repository.
2. Create a branch update-Concept-Transformer
3. Update file linkall-labs/docs/blob/main/content/introduction/concepts.md
4. In the section Transformer.
5. Replace the content.

To understand transform read the following page > https://www.linkall.com/how-to/manage-subscription/transformer

**Comment by c0d33ngr** [comment]
I'd love to work on this, please assign this to me

**Comment by Michaelg22** [comment]
I assign it to you @c0d33ngr

**Comment by Michaelg22** [comment]
Did you join our slack community?

**Comment by c0d33ngr** [comment]
> Did you join our slack community?

Yes I joined

**Comment by c0d33ngr** [comment]
@Michaelg22  for clarity sake, I'm to explain the ideas about Transformer, Define, Function and Template in concepts.md file?

**Comment by Michaelg22** [comment]
> Hello @Michaelg22, for clarity sake I'm to explain the ideas about Transformer, Define, Function and Template in concepts.md file?

Yes your to explain the concept of Transformer by reading the How to transformer document
