### ISSUE TITLE
docs: Add reference links in Introduction page

### ISSUE THREAD

**Issue by ehisakhile** [linkall-labs/docs#225]
## Documentation

Please answer these questions before submitting your issue. Thanks!

### 1. What kind of enhancement do you need to improve Vanus documentation? (Required)

- [ ] Fix typos or format(punctuation, space, indentation, code block, etc.)
- [ ] Update inappropriate or misunderstanding content
- [x] Add missing content or new documents
- [ ] Delete useless content or outdated documents
- [ ] Localize or translate documents

**Comment by ehino** [comment]
I am adding reference links to the introduction page to help beginners understand some terms which will help them understand Vanus.
