### ISSUE TITLE
[Good First Issues]: Review the document What is Vanus 1 - 3 points

### ISSUE THREAD

**Issue by Michaelg22** [linkall-labs/docs#227]
# Documentation

## Motivation

The best way to learn about an open-source project starts with reading its documentation. In order to better know about Vanus and improve the quality of Vanus documentation, we're looking for OSS enthusiasts to review our docs.

## Details

Review the document "what is Vanus" and check for inappropriate content, grammar mistake, and document style.

How to change it:

Fork the docs repository.
Create a branch Review-What-is-Vanus
Review document [What is Vanus](https://github.com/linkall-labs/docs/edit/main/content/introduction/what-is-vanus.md)
Change: inappropriate content, grammar mistake, and document style.

## Event
This issue will be worth 1 - 3 points in the current event.

**Comment by c0d33ngr** [comment]
Hello, I'd love to work on this, please assign it to me

**Comment by c0d33ngr** [comment]
> # Documentation
> ## Motivation
> 
> The best way to learn about an open-source project starts with reading its documentation. In order to better know about Vanus and improve the quality of Vanus documentation, we're looking for OSS enthusiasts to review our docs.
> ## Details
> 
> Review the document "what is Vanus" and check for inappropriate content, grammar mistake, and document style.
> 
> How to change it:
> 
> Fork the docs repository. Create a branch Review-What-is-Vanus Review document [What is Vanus](https://github.com/linkall-labs/docs/edit/main/content/introduction/what-is-vanus.md) Change: inappropriate content, grammar mistake, and document style.
> ## Event
> 
> This issue will be worth 1 - 3 points in the current event.

Hello sir, I'd love to work on this, please assign to me.

**Comment by Michaelg22** [comment]
Yes I will assign it to you
